name: Pre release

# Run this workflow every time when changes land on master
on:
  push:
    branches:
      - master

jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
