name: Publish

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  publish:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Set node version
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
